Symfony: MVC

== Install Symfony

https://symfony.com/doc/current/setup.html

=== create new project: `symfony new MVC --web-app`

I will use de build-in server, so I don't have to create a vhost.
You call it by the command : `symfony server:start`

== Use the MVC
=== create a controller, a method and a Router
While a controller can be any PHP callable (function, method on an object, or a Closure),
a controller is usually a method inside a controller class.

. Create a symfony controller called "LearningController"
 bin/console make:controller

. Create a method called "aboutMe"

. This page should be reachable by adding "/about-me" to the url.
For this, I needed Routes:

==== Routes
Routes can be configured in YAML, XML, PHP or using attributes.
 I used attributes, so I can put the route and controller in the same place (In a controller class).



== Twig

. I installed the twig package with: `composer require twig`
. to use a template, I created a template (exercise.html.twig) and I called in the method.
`return $this->render('example.html.twig', ['name' => 'BeCode']);`


== extra challenge: SECURITY

- [x] registration form
- [x] user
- [] login
- [] logout
- [] beveiligd pad (rollen)

To get started, I installed the SecurityBundle:

`composer require symfony/security-bundle`

Three elements are needed:

. user

The easiest way to generate a user class is using the `make:user` command from the MakerBundle:

 $ php bin/console make:user

Any secured section of your application needs some concept of a user.
The user provider loads users from any storage (e.g. the database) based on a "user identifier"
(e.g. the user's email address);

If your user is a Doctrine entity, (like in this exercise)
we need to create the tables by creating and running a migration:
https://www.doctrine-project.org/projects/doctrine-orm/en/2.12/tutorials/getting-started.html

BEFORE WE START, you have to give acces to the database.
in the .env, you have to comment the connections you don't use and adapt the one u use...

  DATABASE_URL="mysql://'username':'password'@127.0.0.1:3306/'schemaname'?serverVersion=mariadb-10.4.24"


 $ php bin/console make:migration

 $ php bin/console doctrine:migrations:migrate

.. I have to make a registration form, for this, I require a form validator from symfony

composer require form validator

Now I can run the command `php bin/console make:registration-form`

Now I have a registration Form.



. firewall

The firewalls section of config/packages/security.yaml is the most important section.

.. I installed a main security
.. next step is to authenticate the users

... Form login

 $ php bin/console make:controller Login

- adapt/specified the login-path
- edit the login controller
- update the template (login/index.html.twig)

The whole process:

- The user tries to access a resource that is protected (e.g. /admin);
- The firewall initiates the authentication process by redirecting the user to the login form (/login);
- The /login page renders login form via the route and controller created in this example;
- The user submits the login form to /login;
- The security system (i.e. the form_login authenticator) intercepts the request, checks the user's submitted credentials,
  authenticates the user if they are correct, and sends the user back to the login form if they are not.

... protect login against CSRF attacks

Login CSRF attacks can be prevented using the same technique of adding hidden CSRF tokens into the login forms.
The Security component already provides CSRF protection, but it needs to be configured before using it.

-  enable CSRF on the form login

















== add functionality

=== Matching HTTP Methods
By default, routes match any HTTP verb (GET, POST, PUT, etc.) Use the methods option to restrict the verbs
each route should respond to:


NOTE: HTML forms only support GET and POST methods.
If you're calling a route with a different method from an HTML form, add a hidden field called _method
with the method to use (e.g. <input type="hidden" name="_method" value="PUT"/>).
f you create your forms with Symfony Forms this is done automatically for you.
